override HOST_PRIMARY_ARCH := host_x86_64
override HOST_32BIT_ARCH := host_i386
override HOST_FORCE_32BIT := -m32
override TARGET_PRIMARY_ARCH := target_aarch64
override TARGET_SECONDARY_ARCH :=
override TARGET_ALL_ARCH := target_aarch64
override TARGET_FORCE_32BIT :=
override METAG_VERSION_NEEDED := 2.8.1.0.3
override MIPS_VERSION_NEEDED := 2014.07-1
override KERNELDIR := /home/feng/linux/allwinner/a133/a133-linux-tina5.0-v0.9-release1.0/tina/kernel/linux-4.9
override KERNEL_ID := 4.9.191
override PVRSRV_MODULE_BASEDIR := /lib/modules/4.9.191/extra/
override KERNEL_COMPONENTS := srvkm dc_sunxi
override KERNEL_CROSS_COMPILE := /home/feng/linux/allwinner/a133/a133-linux-tina5.0-v0.9-release1.0/tina/out/toolchain/gcc-linaro-6.4.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
override PVRSRV_MODNAME := pvrsrvkm
override PVRSYNC_MODNAME := pvr_sync
override PVR_BUILD_DIR := sunxi_linux
override PVR_BUILD_TYPE := release
override SUPPORT_RGX := 1
override DISPLAY_CONTROLLER := dc_sunxi
override PVR_SYSTEM := rgx_sunxi
override PVR_LOADER :=
override BUILD := release
override DEBUGLINK := 1
override SUPPORT_PHYSMEM_TEST := 1
override VMM_TYPE := stub
override undefine PDUMP
override SUPPORT_DISPLAY_CLASS := 1
override RGX_TIMECORR_CLOCK := mono
override PDVFS_COM_HOST := 1
override PDVFS_COM_AP := 2
override PDVFS_COM_PMC := 3
override PDVFS_COM := PDVFS_COM_HOST
override PVR_GPIO_MODE_GENERAL := 1
override PVR_GPIO_MODE_POWMON_PIN := 2
override PVR_GPIO_MODE := PVR_GPIO_MODE_GENERAL
override PVR_HANDLE_BACKEND := generic
override SUPPORT_DMABUF_BRIDGE := 1
override SUPPORT_SERVER_SYNC_IMPL := 1
override SUPPORT_FALLBACK_FENCE_SYNC := 1
override PVR_USE_FENCE_SYNC_MODEL := 1
